name: Compliance
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm@9.15.4
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm@9.15.4
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
      - name: Coverage
        run: pnpm run coverage

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22 ]
        redis-version: [ 4, 5 ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g pnpm@9.15.4

      - name: Start Redis v${{ matrix.redis-version }}
        uses: superchargejs/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run integration
